version: "3.5"

services:
  # postgres:
  #   container_name: postgres_container
  #   image: postgres
  #   env_file:
  #     - docker.env
  #   environment:
  #     TZ: Asia/Seoul
  #     PGTZ: Asia/Seoul
  #     PGDATA: /data/postgres
  #   volumes:
  #     - ./postgres:/data/postgres
  #   expose:
  #     - "5432"
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4
  #   env_file:
  #     - docker.env
  #   environment:
  #     PGADMIN_CONFIG_SERVER_MODE: "False"
  #   volumes:
  #     - ./pgadmin:/var/lib/pgadmin
  #   expose:
  #     - "5050"
  #   ports:
  #     - "5050:80"
  #   restart: unless-stopped

  # redis:
  #   container_name: redis
  #   image: redis:7.2.4-alpine
  #   expose:
  #     - "6379"
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./redis/data:/data
  #     - ./redis/redis.conf:/etc/redis/redis.conf
  #   restart: always
  #   command: redis-server /etc/redis/redis.conf
  #   jenkins:
  #     container_name: jenkins
  #     image: jenkins/jenkins:lts
  #     # env_file:
  #     #   - docker.env
  #     environment:
  #       JAVA_OPTS: "-Djenkins.install.runSetupWizard=false" # Jenkins 초기 설정 마법사 비활성화
  #     volumes:
  #       - ./jenkins_home:/var/jenkins_home # Jenkins 데이터 디렉토리 마운트
  #     ports:
  #       - "8080:8080" # Jenkins 웹 인터페이스 포트
  #       - "50000:50000" # Jenkins 에이전트와의 연결 포트
  #     restart: unless-stopped
  #     networks:
  #       - jenkins-network

  # networks:
  #   jenkins-network:
  #     driver: bridge
