export enum ErrorCodeEnum {
  NOT_FOUND = "NOT_FOUND",
  UNAUTHORIZED = "UNAUTHORIZED",
  ALREADY_REGISTERED = "ALREADY_REGISTERED",

  DB_ERROR = "DB_ERROR",

  INVALID_DATA_TYPE = "INVALID_DATA_TYPE",
}
